import {
  BarChart3Icon,
  BrainIcon,
  BuildingIcon,
  CloudIcon,
  CodeIcon,
  DollarSignIcon,
  FileTextIcon,
  GlobeIcon,
  HeadphonesIcon,
  PencilIcon,
  PhoneIcon,
  ShieldCheckIcon,
  TargetIcon,
  TruckIcon,
  UsersIcon,
} from "lucide-react";

const domains = [
  {
    icon: TargetIcon,
    label: "Digital Marketing",
    value: "digital-marketing",
    search: "I want better marketing results.",
    description: "Smart advertising that reaches the right customers at the right time.",
  },
  {
    icon: CodeIcon,
    label: "Software Development",
    value: "software-development",
    search: "I need custom software solutions.",
    description: "Custom applications and systems built to streamline your business operations.",
  },
  {
    icon: BarChart3Icon,
    label: "Business Analytics",
    value: "business-analytics",
    search: "I need data insights for my business.",
    description: "Turn your data into actionable insights to drive better business decisions.",
  },
  {
    icon: ShieldCheckIcon,
    label: "Cybersecurity",
    value: "cybersecurity",
    search: "I need to protect my business from cyber threats.",
    description: "Comprehensive security solutions to protect your business from digital threats.",
  },
  {
    icon: UsersIcon,
    label: "Human Resources",
    value: "human-resources",
    search: "I need help managing my workforce.",
    description: "Complete HR solutions from recruitment to employee management and development.",
  },
  {
    icon: PencilIcon,
    label: "Content Creation",
    value: "content-creation",
    search: "I need quality content for my business.",
    description: "Professional content writing, design, and multimedia production services.",
  },
  {
    icon: TruckIcon,
    label: "Supply Chain Management",
    value: "supply-chain-management",
    search: "I need to optimize my supply chain.",
    description: "Streamline your logistics and inventory management for maximum efficiency.",
  },
  {
    icon: DollarSignIcon,
    label: "Financial Services",
    value: "financial-services",
    search: "I need financial planning and management.",
    description: "Accounting, bookkeeping, and financial consulting to keep your business profitable.",
  },
  {
    icon: PhoneIcon,
    label: "Customer Service",
    value: "customer-service",
    search: "I need better customer support solutions.",
    description: "Professional customer service and support solutions to enhance client satisfaction.",
  },
  {
    icon: CloudIcon,
    label: "Cloud Services",
    value: "cloud-services",
    search: "I need cloud infrastructure and migration.",
    description: "Cloud migration, management, and optimization services for scalable business growth.",
  },
  {
    icon: BrainIcon,
    label: "Business Consulting",
    value: "business-consulting",
    search: "I need strategic business advice.",
    description: "Expert guidance to optimize operations, strategy, and growth opportunities.",
  },
  {
    icon: BuildingIcon,
    label: "Real Estate Services",
    value: "real-estate-services",
    search: "I need commercial real estate solutions.",
    description: "Commercial property management, leasing, and investment advisory services.",
  },
  {
    icon: GlobeIcon,
    label: "International Trade",
    value: "international-trade",
    search: "I need help with global business operations.",
    description: "Import/export facilitation, international compliance, and global market entry.",
  },
  {
    icon: FileTextIcon,
    label: "Legal Services",
    value: "legal-services",
    search: "I need legal support for my business.",
    description: "Corporate law, contracts, compliance, and legal advisory services for businesses.",
  },
  {
    icon: HeadphonesIcon,
    label: "Training & Development",
    value: "training-development",
    search: "I need employee training programs.",
    description: "Professional development and training programs to enhance your team's skills.",
  },
];

export default domains;
