import {
  BarChartIcon,
  BookIcon,
  BotIcon,
  BriefcaseIcon,
  CalendarIcon,
  ClockIcon,
  DatabaseIcon,
  DollarSignIcon,
  EyeIcon,
  FileTextIcon,
  GlobeIcon,
  GraduationCapIcon,
  HeadphonesIcon,
  ImageIcon,
  LightbulbIcon,
  MailIcon,
  MessageCircleIcon,
  MicIcon,
  PaletteIcon,
  PieChartIcon,
  SearchIcon,
  SettingsIcon,
  ShieldIcon,
  ShoppingCartIcon,
  SmartphoneIcon,
  TargetIcon,
  TrendingUpIcon,
  UsersIcon,
  VoicemailIcon,
  ZapIcon,
} from "lucide-react";

const domainsOld = [
  {
    icon: MessageCircleIcon,
    label: "Customer Support",
    value: "customer-support",
    search: "I want to automate customer service.",
    description: "AI assistants that answer customer questions 24/7 and handle common inquiries.",
  },
  {
    icon: BotIcon,
    label: "Task Automation",
    value: "task-automation",
    search: "I want to automate repetitive tasks.",
    description: "Let AI handle boring, repetitive work so your team can focus on important things.",
  },
  {
    icon: ImageIcon,
    label: "Content Creation",
    value: "content-creation",
    search: "I need help creating marketing materials.",
    description: "AI tools that create social media posts, product photos, and marketing designs.",
  },
  {
    icon: BarChartIcon,
    label: "Business Intelligence",
    value: "business-intelligence",
    search: "I want to understand my business data better.",
    description: "Turn your business data into easy-to-understand insights and reports.",
  },
  {
    icon: ShoppingCartIcon,
    label: "Online Store Optimization",
    value: "online-store-optimization",
    search: "I want to improve my online sales.",
    description: "AI that suggests products to customers and improves their shopping experience.",
  },
  {
    icon: TargetIcon,
    label: "Digital Marketing",
    value: "digital-marketing",
    search: "I want better marketing results.",
    description: "Smart advertising that reaches the right customers at the right time.",
  },
  {
    icon: BriefcaseIcon,
    label: "Customer Management",
    value: "customer-management",
    search: "I want to manage customers better.",
    description: "Keep track of customer interactions and identify opportunities to grow sales.",
  },
  {
    icon: TrendingUpIcon,
    label: "Sales Forecasting",
    value: "sales-forecasting",
    search: "I want to predict future sales.",
    description: "Predict future sales trends to help you plan inventory and cash flow.",
  },
  {
    icon: ShieldIcon,
    label: "Fraud Protection",
    value: "fraud-protection",
    search: "I need to protect my business from fraud.",
    description: "Automatically detect suspicious transactions and protect your business.",
  },
  {
    icon: EyeIcon,
    label: "Quality Control",
    value: "quality-control",
    search: "I want to improve product quality.",
    description: "AI that checks product quality and identifies defects automatically.",
  },
  {
    icon: BookIcon,
    label: "Document Processing",
    value: "document-processing",
    search: "I want to process documents faster.",
    description: "Automatically read and process invoices, contracts, and other business documents.",
  },
  {
    icon: VoicemailIcon,
    label: "Phone Support",
    value: "phone-support",
    search: "I want AI to handle phone calls.",
    description: "AI assistants that can answer phone calls and help customers with basic requests.",
  },
  {
    icon: GraduationCapIcon,
    label: "Staff Training",
    value: "staff-training",
    search: "I want to train my employees better.",
    description: "AI-powered training programs that help your team learn new skills faster.",
  },
  {
    icon: LightbulbIcon,
    label: "Product Recommendations",
    value: "product-recommendations",
    search: "I want to suggest products to customers.",
    description: "Show customers products they're likely to buy based on their preferences.",
  },
  {
    icon: MailIcon,
    label: "Email Marketing",
    value: "email-marketing",
    search: "I want to automate email campaigns.",
    description: "Create personalized email campaigns that engage customers and drive sales.",
  },
  {
    icon: SearchIcon,
    label: "Search Optimization",
    value: "search-optimization",
    search: "I want to improve my website's search functionality.",
    description: "AI-powered search that helps customers find exactly what they're looking for.",
  },
  {
    icon: CalendarIcon,
    label: "Appointment Scheduling",
    value: "appointment-scheduling",
    search: "I want to automate appointment booking.",
    description: "Let customers book appointments automatically while avoiding conflicts.",
  },
  {
    icon: DollarSignIcon,
    label: "Price Optimization",
    value: "price-optimization",
    search: "I want to optimize my pricing strategy.",
    description: "Set the right prices to maximize profits while staying competitive.",
  },
  {
    icon: UsersIcon,
    label: "HR & Recruitment",
    value: "hr-recruitment",
    search: "I want to streamline hiring and HR processes.",
    description: "Automate resume screening, candidate matching, and employee onboarding.",
  },
  {
    icon: DatabaseIcon,
    label: "Data Analytics",
    value: "data-analytics",
    search: "I want to analyze my business data.",
    description: "Transform raw data into actionable insights for better decision making.",
  },
  {
    icon: ClockIcon,
    label: "Workflow Automation",
    value: "workflow-automation",
    search: "I want to automate business workflows.",
    description: "Connect different tools and automate complex business processes.",
  },
  {
    icon: HeadphonesIcon,
    label: "Voice Assistants",
    value: "voice-assistants",
    search: "I want voice-activated AI assistance.",
    description: "Voice-controlled AI that can handle tasks through speech commands.",
  },
  {
    icon: PaletteIcon,
    label: "Design Automation",
    value: "design-automation",
    search: "I want AI to help with design work.",
    description: "Generate logos, layouts, and visual content automatically.",
  },
  {
    icon: GlobeIcon,
    label: "Website Personalization",
    value: "website-personalization",
    search: "I want to personalize my website for visitors.",
    description: "Show different content to each visitor based on their interests and behavior.",
  },
  {
    icon: SmartphoneIcon,
    label: "Mobile App Features",
    value: "mobile-app-features",
    search: "I want to add AI features to my mobile app.",
    description: "Enhance your mobile app with smart features like chatbots and recommendations.",
  },
  {
    icon: MicIcon,
    label: "Speech Recognition",
    value: "speech-recognition",
    search: "I want to convert speech to text.",
    description: "Convert spoken words into text for transcription and voice commands.",
  },
  {
    icon: SettingsIcon,
    label: "Process Optimization",
    value: "process-optimization",
    search: "I want to optimize my business processes.",
    description: "Find inefficiencies in your operations and suggest improvements.",
  },
  {
    icon: FileTextIcon,
    label: "Content Moderation",
    value: "content-moderation",
    search: "I need to moderate user-generated content.",
    description: "Automatically review and filter inappropriate content on your platform.",
  },
  {
    icon: PieChartIcon,
    label: "Performance Tracking",
    value: "performance-tracking",
    search: "I want to track business performance metrics.",
    description: "Monitor key performance indicators and get alerts when things change.",
  },
  {
    icon: ZapIcon,
    label: "Real-time Notifications",
    value: "real-time-notifications",
    search: "I want intelligent notification systems.",
    description: "Send smart alerts and notifications based on important events and patterns.",
  },
];

export default domainsOld;
