import {
  ActivityIcon,
  AlertCircleIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  AwardIcon,
  BarChartIcon,
  BatteryIcon,
  BellIcon,
  BluetoothIcon,
  BookmarkIcon,
  CalendarIcon,
  CameraIcon,
  CheckCircleIcon,
  CheckIcon,
  ClockIcon,
  CopyIcon,
  CreditCardIcon,
  DollarSignIcon,
  DownloadIcon,
  EditIcon,
  ExternalLinkIcon,
  EyeIcon,
  EyeOffIcon,
  FileIcon,
  FilterIcon,
  FolderIcon,
  GiftIcon,
  HeartIcon,
  HomeIcon,
  ImageIcon,
  InfoIcon,
  KeyIcon,
  LockIcon,
  MailIcon,
  MapPinIcon,
  MessageSquareIcon,
  MinusIcon,
  PackageIcon,
  PauseIcon,
  PhoneIcon,
  PieChartIcon,
  PlayIcon,
  PlusIcon,
  RefreshCwIcon,
  SearchIcon,
  SettingsIcon,
  ShareIcon,
  ShieldIcon,
  ShoppingCartIcon,
  SkipBackIcon,
  SkipForwardIcon,
  SortAscIcon,
  StarIcon,
  StopCircleIcon,
  TagIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
  TrashIcon,
  TrendingDownIcon,
  TrendingUpIcon,
  TruckIcon,
  UnlockIcon,
  UploadIcon,
  UserIcon,
  Volume2Icon,
  VolumeIcon,
  VolumeXIcon,
  WifiIcon,
  XCircleIcon,
  XIcon,
  ZapIcon,
} from "lucide-react";

const icons = [
  {
    icon: HeartIcon,
    label: "Heart",
    value: "heart",
  },
  {
    icon: StarIcon,
    label: "Star",
    value: "star",
  },
  {
    icon: UserIcon,
    label: "User",
    value: "user",
  },
  {
    icon: SettingsIcon,
    label: "Settings",
    value: "settings",
  },
  {
    icon: HomeIcon,
    label: "Home",
    value: "home",
  },
  {
    icon: SearchIcon,
    label: "Search",
    value: "search",
  },
  {
    icon: BellIcon,
    label: "Bell",
    value: "bell",
  },
  {
    icon: MessageSquareIcon,
    label: "Message",
    value: "message",
  },
  {
    icon: PlusIcon,
    label: "Plus",
    value: "plus",
  },
  {
    icon: MinusIcon,
    label: "Minus",
    value: "minus",
  },
  {
    icon: EditIcon,
    label: "Edit",
    value: "edit",
  },
  {
    icon: TrashIcon,
    label: "Trash",
    value: "trash",
  },
  {
    icon: DownloadIcon,
    label: "Download",
    value: "download",
  },
  {
    icon: UploadIcon,
    label: "Upload",
    value: "upload",
  },
  {
    icon: ShareIcon,
    label: "Share",
    value: "share",
  },
  {
    icon: CopyIcon,
    label: "Copy",
    value: "copy",
  },
  {
    icon: CheckIcon,
    label: "Check",
    value: "check",
  },
  {
    icon: XIcon,
    label: "Close",
    value: "close",
  },
  {
    icon: ArrowRightIcon,
    label: "Arrow Right",
    value: "arrow-right",
  },
  {
    icon: ArrowLeftIcon,
    label: "Arrow Left",
    value: "arrow-left",
  },
  {
    icon: ArrowUpIcon,
    label: "Arrow Up",
    value: "arrow-up",
  },
  {
    icon: ArrowDownIcon,
    label: "Arrow Down",
    value: "arrow-down",
  },
  {
    icon: CalendarIcon,
    label: "Calendar",
    value: "calendar",
  },
  {
    icon: ClockIcon,
    label: "Clock",
    value: "clock",
  },
  {
    icon: MailIcon,
    label: "Mail",
    value: "mail",
  },
  {
    icon: PhoneIcon,
    label: "Phone",
    value: "phone",
  },
  {
    icon: MapPinIcon,
    label: "Location",
    value: "location",
  },
  {
    icon: CameraIcon,
    label: "Camera",
    value: "camera",
  },
  {
    icon: ImageIcon,
    label: "Image",
    value: "image",
  },
  {
    icon: FileIcon,
    label: "File",
    value: "file",
  },
  {
    icon: FolderIcon,
    label: "Folder",
    value: "folder",
  },
  {
    icon: LockIcon,
    label: "Lock",
    value: "lock",
  },
  {
    icon: UnlockIcon,
    label: "Unlock",
    value: "unlock",
  },
  {
    icon: EyeIcon,
    label: "Eye",
    value: "eye",
  },
  {
    icon: EyeOffIcon,
    label: "Eye Off",
    value: "eye-off",
  },
  {
    icon: ThumbsUpIcon,
    label: "Thumbs Up",
    value: "thumbs-up",
  },
  {
    icon: ThumbsDownIcon,
    label: "Thumbs Down",
    value: "thumbs-down",
  },
  {
    icon: BookmarkIcon,
    label: "Bookmark",
    value: "bookmark",
  },
  {
    icon: TagIcon,
    label: "Tag",
    value: "tag",
  },
  {
    icon: FilterIcon,
    label: "Filter",
    value: "filter",
  },
  {
    icon: SortAscIcon,
    label: "Sort",
    value: "sort",
  },
  {
    icon: RefreshCwIcon,
    label: "Refresh",
    value: "refresh",
  },
  {
    icon: ExternalLinkIcon,
    label: "External Link",
    value: "external-link",
  },
  {
    icon: InfoIcon,
    label: "Info",
    value: "info",
  },
  {
    icon: AlertCircleIcon,
    label: "Alert",
    value: "alert",
  },
  {
    icon: CheckCircleIcon,
    label: "Success",
    value: "success",
  },
  {
    icon: XCircleIcon,
    label: "Error",
    value: "error",
  },
  {
    icon: PlayIcon,
    label: "Play",
    value: "play",
  },
  {
    icon: PauseIcon,
    label: "Pause",
    value: "pause",
  },
  {
    icon: StopCircleIcon,
    label: "Stop",
    value: "stop",
  },
  {
    icon: SkipForwardIcon,
    label: "Skip Forward",
    value: "skip-forward",
  },
  {
    icon: SkipBackIcon,
    label: "Skip Back",
    value: "skip-back",
  },
  {
    icon: VolumeIcon,
    label: "Volume",
    value: "volume",
  },
  {
    icon: Volume2Icon,
    label: "Volume High",
    value: "volume-high",
  },
  {
    icon: VolumeXIcon,
    label: "Volume Mute",
    value: "volume-mute",
  },
  {
    icon: WifiIcon,
    label: "WiFi",
    value: "wifi",
  },
  {
    icon: BluetoothIcon,
    label: "Bluetooth",
    value: "bluetooth",
  },
  {
    icon: BatteryIcon,
    label: "Battery",
    value: "battery",
  },
  {
    icon: ZapIcon,
    label: "Zap",
    value: "zap",
  },
  {
    icon: TrendingUpIcon,
    label: "Trending Up",
    value: "trending-up",
  },
  {
    icon: TrendingDownIcon,
    label: "Trending Down",
    value: "trending-down",
  },
  {
    icon: BarChartIcon,
    label: "Bar Chart",
    value: "bar-chart",
  },
  {
    icon: PieChartIcon,
    label: "Pie Chart",
    value: "pie-chart",
  },
  {
    icon: ActivityIcon,
    label: "Activity",
    value: "activity",
  },
  {
    icon: AwardIcon,
    label: "Award",
    value: "award",
  },
  {
    icon: ShieldIcon,
    label: "Shield",
    value: "shield",
  },
  {
    icon: KeyIcon,
    label: "Key",
    value: "key",
  },
  {
    icon: CreditCardIcon,
    label: "Credit Card",
    value: "credit-card",
  },
  {
    icon: ShoppingCartIcon,
    label: "Shopping Cart",
    value: "shopping-cart",
  },
  {
    icon: PackageIcon,
    label: "Package",
    value: "package",
  },
  {
    icon: TruckIcon,
    label: "Truck",
    value: "truck",
  },
  {
    icon: GiftIcon,
    label: "Gift",
    value: "gift",
  },
  {
    icon: DollarSignIcon,
    label: "Dollar",
    value: "dollar",
  },
];

export default icons;
