const topicsValues = [
  "Accessibility",
  "Agile Methodologies",
  "API Design",
  "Backend Development",
  "Blockchain",
  "Business Analysis",
  "Business Development",
  "Business Intelligence",
  "Business Strategy",
  "Cloud Platforms",
  "Code Review",
  "Competitive Analysis",
  "Containerization",
  "Continuous Deployment",
  "Continuous Integration",
  "Customer Success",
  "Data Science",
  "Database Management",
  "DevOps & CI/CD",
  "Documentation",
  "Entrepreneurship",
  "Error Handling",
  "Finance",
  "Frontend Frameworks",
  "Go-to-Market",
  "Growth Hacking",
  "Internationalization",
  "Leadership",
  "Legal & Compliance",
  "Machine Learning",
  "Market Research",
  "Marketing",
  "Microservices",
  "Mobile Development",
  "Monitoring & Logging",
  "Networking",
  "Open Source Projects",
  "Operations",
  "Partnerships",
  "Performance Optimization",
  "Pricing Strategy",
  "Product Management",
  "Project Management",
  "Sales",
  "Security Best Practices",
  "Serverless Architecture",
  "Stakeholder Management",
  "Testing & QA",
  "UI/UX Design",
  "Version Control",
  "WebAssembly",
];

export default topicsValues;
